name: crisp_chat
description: A flutter plugin package for using crisp chat natively on Android & iOS.
version: 2.2.1
homepage: https://github.com/alamin-karno/flutter-crisp-chat

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.alaminkarno.flutter_crisp_chat
        pluginClass: FlutterCrispChatPlugin
      ios:
        pluginClass: FlutterCrispChatPlugin

topics:
  - crisp
  - crisp-chat
  - chat
  - communication

funding:
  - https://buymeacoffee.com/alaminkarno
  - https://www.patreon.com/alamin_karno

false_secrets:
  - /example/lib/firebase_options.dart
  - /example/android/app/google-services.json

