name: crisp_chat
description: A flutter plugin package for using crisp chat natively on Android & iOS.
version: 2.4.4

readme: README.md
license: MIT

homepage: https://github.com/alamin-karno/flutter-crisp-chat
issue_tracker: https://github.com/alamin-karno/flutter-crisp-chat/issues
repository: https://github.com/alamin-karno/flutter-crisp-chat
documentation: https://pub.dev/documentation/crisp_chat/latest/



environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <7.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.alaminkarno.flutter_crisp_chat
        pluginClass: FlutterCrispChatPlugin
      ios:
        pluginClass: FlutterCrispChatPlugin

topics:
  - crisp
  - crisp-chat
  - chat
  - communication

funding:
  - https://buymeacoffee.com/alaminkarno
  - https://www.patreon.com/alamin_karno

false_secrets:
  - /example/lib/firebase_options.dart
  - /example/android/app/google-services.json

